#!/usr/bin/env node
// Generates fixtures/sheets.ts: two small workbooks as base64, for the promo's
// spreadsheet beat. BEFORE is the file "the user attached"; AFTER is what the
// assistant's Edit tool card leaves behind (sorted by amount, a Total row,
// the top three amounts bold). Run from desktop/:  node src/renderer/dev/workbench/fixtures/sheets/make.mjs
// Fix: exceljs is CJS with a two-level `module.exports = require(...)` chain
// that Node's ESM/cjs-module-lexer interop can't statically resolve into named
// exports (verified: `import { Workbook } from 'exceljs'` gives `undefined`
// under plain `node`, though it works under vitest's own interop) — import the
// default and destructure instead.
import pkg from 'exceljs';
const { Workbook } = pkg;
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROWS = [
  ['West', 'Priya', 128, 'Jul'], ['East', 'Marcus', 96, 'Jul'], ['North', 'Lena', 41, 'Jul'],
  ['South', 'Diego', 151, 'Jul'], ['Central', 'Aisha', 88, 'Jul'], ['West', 'Priya', 112, 'Aug'],
  ['East', 'Marcus', 134, 'Aug'], ['North', 'Lena', 57, 'Aug'], ['South', 'Diego', 122, 'Aug'],
  ['Central', 'Aisha', 91, 'Aug'], ['West', 'Priya', 143, 'Sep'], ['East', 'Marcus', 108, 'Sep'],
  ['North', 'Lena', 63, 'Sep'], ['South', 'Diego', 167, 'Sep'], ['Central', 'Aisha', 99, 'Sep'],
];

async function book(rows, { total, bold }) {
  const wb = new Workbook(); const ws = wb.addWorksheet('Q3');
  ws.columns = [{ width: 12 }, { width: 12 }, { width: 10 }, { width: 8 }];
  ws.addRow(['Region', 'Rep', 'Amount', 'Month']).font = { bold: true };
  for (const r of rows) ws.addRow(r);
  if (total) {
    const t = ws.addRow(['Total', '', rows.reduce((a, r) => a + r[2], 0), '']);
    t.font = { bold: true };
  }
  for (const i of bold) ws.getRow(i + 2).getCell(3).font = { bold: true };
  return Buffer.from(await wb.xlsx.writeBuffer()).toString('base64');
}

const before = await book(ROWS, { total: false, bold: [] });
const sorted = [...ROWS].sort((a, b) => b[2] - a[2]);
const after = await book(sorted, { total: true, bold: [0, 1, 2] });
const out = `// GENERATED by fixtures/sheets/make.mjs — do not edit. Two workbooks for the
// promo's spreadsheet beat: the file as attached, and the file after the
// assistant sorts it and adds a Total row. Base64 so the workbench can serve
// real xlsx bytes to XlsxView without a disk.
export const SHEET_BEFORE = '${before}';
export const SHEET_AFTER = '${after}';
`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'sheets.ts'), out);
console.log('wrote fixtures/sheets.ts');
