import { describe, it, expect } from 'vitest';
import {
  describeChatsearchCall, isChatsearchCommand, parseFindQuery, parseFindShortIds, parseShowId, providerLabel, TRUNCATION_MARKERS,
} from '../src/shared/chatsearch-refs';
import type { ToolCallState } from '../src/shared/types';

const CMD = `node "/home/x/.claude/plugins/marketplaces/youcoded/plugins/youcoded-chatsearch/skills/chatsearch/scripts/chatsearch.js" '{"cmd":"find","query":"sync"}'`;
// Rows below are byte-for-byte what chatsearch.js's formatRows() produces: it
// pads every column with padEnd(widestInColumn) and joins columns with TWO
// spaces (chatsearch.js:341), so there are always >=2 spaces after the id —
// never one. Generated by running the real column-width algorithm against
// this fixture's three entries (verified against chatsearch.js 2026-08-25).
const FIND_OUT = [
  'index last refreshed 3d ago — open YouCoded to refresh',
  'a3f2   2026-07-26  youcoded      ✓   Permission ask timeout         #perm #ui',
  '9c14   2026-07-22  youcoded-dev  ?†  Native runtime parity program  #native',
  '1b07f  ----------  my project    ○   Row with no known date',
  'showing 3 of 41 — raise limit or narrow the filters',
].join('\n');
const SHOW_OUT = [
  '773634bb-621e-4d84-8d51-903093478ee8  Chat Search Workstream Status',
  'project:    youcoded-dev  (/home/destin/youcoded-dev)',
  'provider:   claude',
  'created:    2026-08-06T04:53:34.394Z',
].join('\n');
// cmdShow (chatsearch.js:782) pushes a staleness banner and index.problems
// BEFORE the metadata block, so the uuid line is often NOT line 0 in real
// output — this fixture pins that shape.
const SHOW_OUT_WITH_BANNER = [
  'index last refreshed 3d ago — open YouCoded to refresh',
  ...SHOW_OUT.split('\n'),
].join('\n');

// Built as the REAL type on purpose: a wrong status string must fail to compile.
function bash(command: string, response?: string, status: ToolCallState['status'] = 'complete'): ToolCallState {
  return { toolUseId: 't1', toolName: 'Bash', input: { command }, status, response };
}

describe('parseFindShortIds', () => {
  it('returns one id per table row, ignoring banner and trailer, including a dateless row', () => {
    expect(parseFindShortIds(FIND_OUT)).toEqual(['a3f2', '9c14', '1b07f']);
  });
  it('returns [] for the no-index and no-match messages', () => {
    expect(parseFindShortIds('no chatsearch index exists on this device — open YouCoded to build it')).toEqual([]);
    expect(parseFindShortIds('no conversations matched (40 indexed). Try dropping a filter.')).toEqual([]);
  });
});

describe('parseShowId', () => {
  it('reads the full uuid and provider from the metadata block', () => {
    expect(parseShowId(SHOW_OUT)).toEqual({ id: '773634bb-621e-4d84-8d51-903093478ee8', provider: 'claude' });
  });
  it('reads the full uuid and provider even when a staleness banner precedes the block', () => {
    expect(parseShowId(SHOW_OUT_WITH_BANNER)).toEqual({ id: '773634bb-621e-4d84-8d51-903093478ee8', provider: 'claude' });
  });
  it('returns null when no line starts with a uuid', () => {
    expect(parseShowId('unknown id a3f2')).toBeNull();
  });
});

describe('isChatsearchCommand', () => {
  it('is true for argv and stdin-heredoc forms, and with a harmless 2>&1', () => {
    expect(isChatsearchCommand(CMD)).toBe(true);
    expect(isChatsearchCommand(`cat <<'JSON' | node "/x/chatsearch.js"\n{"cmd":"show","id":"7736"}\nJSON`)).toBe(true);
    expect(isChatsearchCommand(`${CMD} 2>&1`)).toBe(true);
  });
  it('is false for pipes or redirects AFTER the script, and for non-chatsearch commands', () => {
    expect(isChatsearchCommand(`${CMD} | head -40`)).toBe(false);
    expect(isChatsearchCommand(`${CMD} > /tmp/out.txt`)).toBe(false);
    expect(isChatsearchCommand('ls -la')).toBe(false);
  });
});

describe('parseFindQuery', () => {
  it('reads the query out of a command-line request and a heredoc alike', () => {
    expect(parseFindQuery(CMD)).toBe('sync');
    expect(parseFindQuery(`cat <<'JSON' | node "/x/chatsearch.js"\n{"cmd":"find","query":"native runtime"}\nJSON`)).toBe('native runtime');
  });
  it('unescapes an escaped quote instead of cutting the query short', () => {
    expect(parseFindQuery(`node "/x/chatsearch.js" '{"query":"the \\"auto\\" mode"}'`)).toBe('the "auto" mode');
  });
  it('returns empty when there is no query to read — the card then prints no line at all', () => {
    expect(parseFindQuery(`node "/x/chatsearch.js" '{"cmd":"find"}'`)).toBe('');
  });
});

describe('describeChatsearchCall', () => {
  it('describes a find call from its output', () => {
    expect(describeChatsearchCall(bash(CMD, FIND_OUT))).toEqual({ cmd: 'find', query: 'sync', shortIds: ['a3f2', '9c14', '1b07f'] });
  });
  it('describes a show call from its output, even when the command says nothing about show', () => {
    const stdinCmd = `cat <<'JSON' | node "/x/chatsearch.js"\n{"cmd":"show","id":"7736"}\nJSON`;
    expect(describeChatsearchCall(bash(stdinCmd, SHOW_OUT))).toEqual({ cmd: 'show', id: '773634bb-621e-4d84-8d51-903093478ee8', provider: 'claude' });
  });
  it('is null for non-Bash tools and non-chatsearch commands', () => {
    expect(describeChatsearchCall({ ...bash(CMD, FIND_OUT), toolName: 'Read' })).toBeNull();
    expect(describeChatsearchCall(bash('ls -la', 'a3f2  2026-07-26  x  ✓  t'))).toBeNull();
  });
  it('is null while running, failed, awaiting approval, or without output', () => {
    expect(describeChatsearchCall(bash(CMD, undefined, 'running'))).toBeNull();
    expect(describeChatsearchCall(bash(CMD, FIND_OUT, 'failed'))).toBeNull();
    expect(describeChatsearchCall(bash(CMD, undefined, 'awaiting-approval'))).toBeNull();
    expect(describeChatsearchCall(bash(CMD, ''))).toBeNull();
  });
  it('is null when the output carries ANY known truncation marker', () => {
    for (const m of TRUNCATION_MARKERS) expect(describeChatsearchCall(bash(CMD, `${FIND_OUT}\n${m}\nmore`))).toBeNull();
  });
  it('is null for chatsearch output that is not a table (no index, empty result)', () => {
    expect(describeChatsearchCall(bash(CMD, 'no chatsearch index exists on this device — open YouCoded to build it'))).toBeNull();
    expect(describeChatsearchCall(bash(CMD, 'no conversations matched (40 indexed).'))).toBeNull();
  });
});

describe('providerLabel', () => {
  it('never shows the raw lane name', () => {
    expect(providerLabel('claude')).toBe('Claude Code');
    expect(providerLabel('native')).toBe('YouCoded assistant');
  });
});
